#!/usr/bin/env python3
import json,re,os
from datetime import datetime,timezone,timedelta
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]; LOG=ROOT/'content-staging/CONTENT_RECONSTRUCTION_AUTOMATION_LOG.md'; MP=ROOT/'content-staging/manifests/MASTER_CONTENT_MANIFEST.json'
SID='0d4fa9fd-a93c-4d18-9dea-6dd22eb2e199'; NAME='الرياضيات نماذج وزارية 1445'; START='ffaac8bb65705533bded9b634164ede2b6923905'; END='fb8aa7338e10e9286f804466cbfde01c8d205333'
def done(s):
 x=str(s.get('review_status') or ''); return x.startswith('processed_') or x=='reconstructed_verified'
def main():
 m=json.loads(MP.read_text(encoding='utf-8')); ss=m['sources']; p=m['reconstruction_progress']; i=next(i for i,s in enumerate(ss) if s['id']==SID); nxt=next(x for x in ss[i+1:]+ss[:i] if not done(x)); nid=nxt['id']; nn=(nxt.get('legacy_source') or {}).get('name') or 'NOT VERIFIED'; nm=json.loads((ROOT/(nxt.get('manifest_path') or f'content-staging/raw/legacy-supabase/subjects/{nid}/manifest.json')).read_text(encoding='utf-8')); c=nm.get('counts') or {}; a=nm.get('anomalies') or {}; baseline=f"{c.get('pages','NOT VERIFIED')} pages, {c.get('images_downloaded',c.get('image_references','NOT VERIFIED'))} images, {c.get('questions','NOT VERIFIED')} legacy questions, {c.get('image_download_failures','NOT VERIFIED')} download failures; anomaly arrays preserved: {json.dumps(a,ensure_ascii=False,sort_keys=True)}"; exam=('نماذج' in nn) or nxt.get('classification')=='exam_source_group'; op=(f'Re-fetch live HEAD and baton; confirm no active/running workflow for {nid}; read live manifest/pages; technically verify immutable RAW; scan duplicates/numbering; generate ordered exam-boundary evidence; resolve Individual Exam Models/correction/Answer-Key evidence only from this source; map questions only where membership is proven; quarantine uncertainty; assert 25,755 invariant; checkpoint and continue.' if exam else f'Re-fetch live HEAD and baton; confirm no active/running workflow for {nid}; read live manifest/pages; technically verify immutable RAW; establish exact source identity; reconstruct Book/Unit/Lesson/page boundaries from source evidence; isolate ambiguous review/non-lesson pages; map questions only where membership is proven; assert 25,755 invariant; checkpoint and continue.')
 cp=f'''## 10. ACTIVE CHECKPOINT\n\n- state: `READY_FOR_NEXT_SOURCE`\n- branch: `content/corpus-inventory-20260914`\n- latest verified work HEAD before this handoff commit: `{END}`\n- last completed source: `{SID} — {NAME}`\n- current source: `{nid} — {nn}`\n- current source baseline from live manifest: `{baseline}`\n- current operation: `{op}`\n- next source: `Resolve from live MASTER_CONTENT_MANIFEST only after the current source is safely finalized.`\n- blockers: `none for forward progress; Mathematics 1445 pages 40..42 remain quarantined review_required and must not be silently merged or renumbered.`\n- owner decision required now: `no`\n'''
 text=LOG.read_text(encoding='utf-8'); pat=r'## 10\. ACTIVE CHECKPOINT\n.*?\n---\n'; assert len(re.findall(pat,text,flags=re.S))==1; text=re.sub(pat,cp+'\n---\n',text,count=1,flags=re.S); now=datetime.now(timezone(timedelta(hours=3))).isoformat(timespec='seconds')
 run=f'''\n## RUN {now} — Worker A\n\n- state: COMPLETE\n- start HEAD: `{START}`\n- end HEAD: `{END}`\n- phase: `CONTENT RECONSTRUCTION + EXAM BOUNDARY DISCOVERY`\n- source at start: `{SID} — {NAME}`\n- completed in this run:\n  - verified Worker B's live handoff and continued from Mathematics 1445;\n  - technically verified 42/42 RAW images and contiguous pages 1..42;\n  - generated discovery/contact-sheet, metadata/provenance and repeated-label pixel evidence;\n  - verified models 1..13 on pages 1..39 from explicit source-local titles;\n  - quarantined pages 40..42 because they repeat model-12 labels with distinct binaries and semantic identity remains NOT VERIFIED; no merge or invented model 14;\n  - structurally linked 28/28 questions to verified model 1; semantic correctness NOT VERIFIED;\n  - updated reconstruction, MASTER and reconstruction/status evidence through exact-head guarded finalization.\n- evidence produced/verified:\n  - technical report, discovery report, metadata evidence, repeated-label evidence and final reconstruction under `content-staging/reconstruction/.../{SID}*`;\n  - discovery runs `34855070932`, `34855530204`; finalization run `34855799041` succeeded.\n- ambiguity/review_required:\n  - pages 40..42 remain `review_required`; repeated model-12 semantic identity NOT VERIFIED;\n  - standalone official Answer Keys and semantic AI-question correctness remain NOT VERIFIED.\n- invariant result: PASS\n- Sources processed: {p['sources_completed']}/58\n- Educational: {p.get('educational_sources_completed',0)}/26\n- Books / Units / Lessons / Lesson Pages: 10 / 33 / 196 / 877\n- Exam Source Groups: {p['exam_source_groups_completed']}/32\n- Individual Exam Models: {p['individual_exam_models']}\n- Exam Pages: {p['exam_pages_completed']}/2,286\n- Verified Answer Keys: 0\n- Source images technical: {p['source_images_technically_verified']}/5,273\n- WebP generated / accepted / rejected: 0 / 0 / 0\n- Legacy Questions: 25,755\n- Lesson-linked: {p.get('lesson_linked_structural',0)}\n- Exam-linked: {p.get('exam_linked_to_individual_model',0)}\n- Review-required: {p.get('review_required',0)}\n- Unclassified: {p.get('unclassified',0)}\n- Duplicate groups classified: {p.get('duplicate_fingerprint_groups_classified',0)}/99\n- RAW mutations: 0\n- Unrelated mutations: 0\n- New imports: 0\n- New publications: 0\n- last completed source: `{SID} — {NAME}`\n- current source: `{nid} — {nn}`\n- exact next operation: `{op}`\n- next source: `Resolve only after current source finalization.`\n- blockers: `none for forward progress; isolated Math 1445 review_required block intentionally remains unresolved.`\n- handoff note: `Worker B must re-fetch live HEAD and this baton, verify Math 1445 counters/evidence, then start {nid} from its own evidence without inheriting Math 1445 boundaries.`\n'''
 LOG.write_text(text.rstrip()+'\n'+run+'\n',encoding='utf-8'); print(json.dumps({'next_source_id':nid,'next_source_name':nn,'baseline':baseline,'progress':p},ensure_ascii=False))
if __name__=='__main__': main()
